### ISSUE TITLE
6.3.x Target Release Date

### ISSUE THREAD

**Issue by provAndrewLeach** [smallrye/smallrye-fault-tolerance#1001]
**_If this is not the best place to ask questions, please let me know, and I'll delete this issue._**

My team is currently using the Fault Tolerance API. We were interested in understanding this quote (from the docs):

> At the moment, the programmatic API of SmallRye Fault Tolerance is not integrated with metrics. This will change in the future, though possibly only in the CDI implementation.

I took a look through the commit history of the project, and it _appears_ that ^ comment is being addressed with the release of 6.3.

Can anyone help me understand when the intended release date of this artifact is so that I can plan accordingly with my team?

Thanks!

**Comment by Ladicek** [comment]
That is correct, the programmatic API will be integrated with metrics in 6.3. Two RC releases have been produced already, so the actual release shouldn't be too far. There's no schedule though; it's done when it's done.

**Comment by provAndrewLeach** [comment]
Thanks for the update @Ladicek!
