### ISSUE TITLE
New implementation that is Reactive based

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-fault-tolerance#102]
As Hystrix is no longer maintained by Netflix, we need to develop a new implementation.

With our desire to be more "reactive" within SmallRye, ideally this would be a reactive focused implementation which likely necessitates developing something new as opposed to re-using any existing library

**Comment by kenfinnigan** [comment]
One thing to consider with this, should we be based on the Vert.x circuit breaker?

FYI @Ladicek @michalszynkiewicz

**Comment by Ladicek** [comment]
We can/should take a look, but I'd like to avoid external dependencies as much as possible.

**Comment by Ladicek** [comment]
New implementation has been merged to `master`, hence closing this.
