### ISSUE TITLE
Allow to customize time in the FaultTolerance instance

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [smallrye/smallrye-fault-tolerance#1049]
We use FaultTolerance for circuit breaker purposes, and we lack support for mocking the stopwatch.

Basically, we want to check something like this in the integration tests:

```
toxiproxy.introduceLatency(...)

repeat (N) { callApi(...) }// api under the hood uses circuit breaker

circuitBreaker(...) shouldBe OPEN

toxiproxy.stop() // stop latency
delay(...) // This needs to be real delay

repeat (M) { callApi(...) } 
circuitBreaker(...) shouldBe CLOSED 
```

Currently, the delay(...) function must wait for the delay. It might be useful to allow to provide mocked time provider to the `FaultTolerance` instance, for example:

```
FaultTolerance.withTimeProvider(interface that returns current millis)
```

**Comment by AleksanderBrzozowski** [comment]
> I don't really want to expose this directly on the main entrypoint to the programmatic API. It might be possible to create a testing API (FaultToleranceTesting?) that would allow this, but no promises.

What is the reason for that? 🙂 

> In the meantime, if you use the annotation-based API (@CircuitBreaker), you can change the circuit breaker delay for tests using MP Config. If you use the programmatic API, I don't think there's a built-in way to change the delay.

Yeah, this is possible 👍

**Comment by Ladicek** [comment]
> > I don't really want to expose this directly on the main entrypoint to the programmatic API. It might be possible to create a testing API (FaultToleranceTesting?) that would allow this, but no promises.
> 
> What is the reason for that? 🙂

I don't think anyone should ever change time without clearly stating that this is only for testing. Production code should be as isolated as possible from this possibility.

**Comment by AleksanderBrzozowski** [comment]
I got your point. From my perspective, we often expose a Clock bean in our services, something like:

```
@Produces
fun clock(): Clock = SystemClock
```

Which in tests is changed to a mocked clock:

```
@Produces
fun mockClock(): Clock = MockedClock
```

I am fine with exposing an interface, or other option just for test purposes. WDYT?

**Comment by Ladicek** [comment]
Sure. The question is, how should the interface look like? Internally, there are 2 interfaces that concern time: `Stopwatch` and `Timer`. Stopwatch is relatively simple, but timer is not.

**Comment by AleksanderBrzozowski** [comment]
I fixed the issue by using await in the test, and waiting for the CircuitBreaker to be HALF_OPEN, something like:

```
eventually(1.seconds) {
  cb shouldBe HALF_OPEN
}
```

IMO this looks good enough. I am ok to close this issue, maybe this is something to consider for the future.
