### ISSUE TITLE
Implement MicroProfile Fault Tolerance 4.1

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#1052]
This includes:

- OpenTelemetry / MP Telemetry support (for metrics)

**Comment by rhusar** [comment]
FYI WildFly could consume this actually right-away in our 'preview' distribution.

**Comment by Ladicek** [comment]
I have a branch that mostly implements this (https://github.com/Ladicek/smallrye-fault-tolerance/commits/add-opentelemetry-support/), the only thing I'm not sure about is how to properly select the metrics provider. Would WildFly need multiple metrics providers at the same time?

**Comment by rhusar** [comment]
> I have a branch that mostly implements this (https://github.com/Ladicek/smallrye-fault-tolerance/commits/add-opentelemetry-support/), the only thing I'm not sure about is how to properly select the metrics provider. Would WildFly need multiple metrics providers at the same time?

Good question, I don't remember MP FT spec saying anything about that or does it? While this shouldn't be too problematic from implementation standpoint, I am not sure if that's a valid use to use multiple metrics providers simultaneously.

**Comment by Ladicek** [comment]
The specification allows using both MP Metrics and MP Telemetry at the same time:

> If all three of MicroProfile Fault Tolerance, MicroProfile Metrics, and MicroProfile Telemetry are used together then MicroProfile Fault Tolerance exports metrics to both MicroProfile Metrics and MicroProfile Telemetry.

And the TCK tests that exact scenario. I think there's actually no support in the TCK for disabling any of the metrics providers, one just has to exclude the tests.

**Comment by rhusar** [comment]
> The specification allows using both MP Metrics and MP Telemetry at the same time:
> 
> > If all three of MicroProfile Fault Tolerance, MicroProfile Metrics, and MicroProfile Telemetry are used together then MicroProfile Fault Tolerance exports metrics to both MicroProfile Metrics and MicroProfile Telemetry.

Actually, it doesn't matter what the spec says here since we don't support MP Metrics in WF anyway. What I was inadvertently answering was whether we need to support *both* Micrometer and MicroProfile Telemetry at the same time. It appears that both of these can be active at the same time, so I think we should actually be able to enable both from SR FT.

> And the TCK tests that exact scenario. I think there's actually no support in the TCK for disabling any of the metrics providers, one just has to exclude the tests.

Right - that's what we are doing and will continue doing in WF.

**Comment by Ladicek** [comment]
OK, understood. I'll have to think about this, because the current design allows exactly one metrics provider and that needs to change. Thanks!

**Comment by Ladicek** [comment]
OK, done. There's one more `FaultToleranceExtension` constructor now, which accepts `Set<MetricsIntegration>`.

The zero-param ctor now discovers present metrics and uses all of them, which sounds like a sensible default. Your choice if you want to pass the `Set<MetricsIntegration>` or rely on auto-detection.

**Comment by rhusar** [comment]
> OK, done. There's one more `FaultToleranceExtension` constructor now, which accepts `Set<MetricsIntegration>`.
> 
> The zero-param ctor now discovers present metrics and uses all of them, which sounds like a sensible default. Your choice if you want to pass the `Set<MetricsIntegration>` or rely on auto-detection.

The metrics provider autodiscovery based on available modules makes sense to me now that the spec defined this a bit better.
