### ISSUE TITLE
Reusable Fault Tolerance: Automatically Set Description for Metrics to Method Names

### ISSUE THREAD

**Issue by AndreasPetersen** [smallrye/smallrye-fault-tolerance#1060]
When using [reusable fault tolerance](https://smallrye.io/docs/smallrye-fault-tolerance/6.5.0/reference/reusable.html), I would like the description of the `FaultTolerance` instance to be automatically bsed on the method name. Consider:

```
@ApplicationScoped
public class PreconfiguredFaultTolerance {
    @Produces
    @Identifier("my-fault-tolerance")
    public static final FaultTolerance<String> FT = FaultTolerance.<String>create()
            .withRetry().maxRetries(2).done()
            .withFallback().handler(() -> "fallback").done()
            .build();
}
```

and 

```
@ApplicationScoped
@ApplyFaultTolerance("my-fault-tolerance")
public class MyService {
    public String doSomething() {
        ...
    }

    public String doSomethingElse() {
        ...
    }
}
```

The generated metrics for `my-fault-tolerance` will be an UUID as per [the documentation](https://smallrye.io/docs/smallrye-fault-tolerance/6.5.0/reference/programmatic-api.html#_metrics). I could add `withDescription("my-fault-tolerance")` to `my-fault-tolerance`, but then I will not be able to distinguish between the `doSomething` and `doSomethingElse` methods.

If instead I used the regular annotations, the method attribute of the metrics is set to the names of the methods as expected.

**Comment by Ladicek** [comment]
That sounds natural, but it goes directly against the current design. A single `FaultTolerance` object has a single `MeteredOperation` and single `MetricsRecorder`, which means there's a single "method name" (the FT description). It doesn't even know it's used via `@ApplyFaultTolerance`.

We might be able to do something on the `@ApplyFaultTolerance` level to override the "method name", need to check.

But currently, this works as designed.

**Comment by AndreasPetersen** [comment]
Wow, amazing that you managed to fix this so fast! Thanks a lot!
