### ISSUE TITLE
testWaitingQueue(io.smallrye.faulttolerance.bulkhead.BulkheadTest) is flaky

### ISSUE THREAD

**Issue by rhusar** [smallrye/smallrye-fault-tolerance#138]
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.873 s <<< FAILURE! - in io.smallrye.faulttolerance.bulkhead.BulkheadTest
[ERROR] testWaitingQueue(io.smallrye.faulttolerance.bulkhead.BulkheadTest)  Time elapsed: 1.991 s  <<< FAILURE!
java.lang.AssertionError
	at io.smallrye.faulttolerance.bulkhead.BulkheadTest.testWaitingQueue(BulkheadTest.java:62)
```

as seen on https://semaphoreci.com/smallrye/smallrye-fault-tolerance/branches/pull-request-137/builds/1

**Comment by rhusar** [comment]
@Ladicek @michalszynkiewicz  Would you just be willing to look into this?  I think Martin – the original author – has moved on :-)

**Comment by Ladicek** [comment]
I've been ignoring this problem, but you're right, someone should take a look :-)

**Comment by rhusar** [comment]
Roughly, how frequent is this? I dont see test history on SemaphoreCI...

**Comment by Ladicek** [comment]
Not very frequent. What's a lot more frequent is JVM crashing during the MP FT TCK, which we attribute to Semaphore CI quirks.

**Comment by rhusar** [comment]
I am getting worried if this is unstable, once this is in WildFly, these tests will run a LOT every day.

**Comment by Ladicek** [comment]
You mean you're going to run SmallRye FT test suite as part of WildFly build?

**Comment by rhusar** [comment]
No – just upstream TCK and container integration specific suite of tests.

**Comment by Ladicek** [comment]
The line with failing assert is:

```java
assertTrue(startLatch.await(500L, TimeUnit.MILLISECONDS));
```

I've lowered the timeout from 500 millis to 50 millis and it starts to fail much more frequently (locally).

Which suggests that perhaps making the timeout bigger would make the problem go away. I don't know in what environment Semaphore CI runs our tests, but if it is some form of high-density setup, perhaps it can occasionally take half a second for 6 threads to arrive to a barrier...

**Comment by rhusar** [comment]
@Ladicek This should stabilize the test https://github.com/smallrye/smallrye-fault-tolerance/pull/139
