### ISSUE TITLE
Intermittent failures of the async CP test

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye-fault-tolerance#169]
From time to time, the async test in the `TracingContextPropagationTest` fails on Semaphore.
So far I was unable to reproduce the problem or figure out what the cause it.

**Comment by michalszynkiewicz** [comment]
I was able to reproduce the failure running in a docker container with 0.1 cpu, I will continue to investigate the issue.

**Comment by Ladicek** [comment]
Fixed in #175.
