### ISSUE TITLE
use JBoss Logging annotation processor for all of logging

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#172]

**Comment by rhusar** [comment]
Did you start working on this? If not, I will take this one (I think I put logging unification on the F2F agenda and also there is an open issue in WF that MP FT is missing logging IDs).

**Comment by Ladicek** [comment]
I didn't, no. Just filing issues for things I know we need to do. Feel free to take this. (If you can't self-assign, let me know and I'll assign you.)

**Comment by Ladicek** [comment]
I don't know if we agreed on a logging prefix for all of SmallRye; there was a logging discussion on the SmallRye Google group. I'll ask, I guess.

**Comment by Ladicek** [comment]
OK, so message codes were discussed in this thread: https://groups.google.com/forum/#!topic/smallrye/YzZ61g-12Sg SmallRye Common uses `SRCOM`, which nicely aligns with what I imagined for Fault Tolerance: `SRFT`.

**Comment by rhusar** [comment]
Sounds good

**Comment by Ladicek** [comment]
In #223, Ken writes:

> Follow the procedures defined in https://github.com/smallrye/smallrye-parent/wiki/I18N-Messages-and-Logging as part of implementing smallrye/smallrye-parent#102 for all SmallRye projects
>
> An example usage can be found in https://github.com/smallrye/smallrye-common

**Comment by Ladicek** [comment]
It seems the convention is to have a 5-char project code, so I captured `SRFTL`, because that's geekier than `SRFLT` :laughing:

**Comment by Ladicek** [comment]
Done in #313.
