### ISSUE TITLE
Global configuration options like io.smallrye.faulttolerance.globalThreadPoolSize does not work for multiple deployments

### ISSUE THREAD

**Issue by rhusar** [smallrye/smallrye-fault-tolerance#183]
One of the limitations we had with Hystrix (of course apart from it being an abandonware) was that its configuration was global and thus shared by every SR FT deployment. This has not been a major problem for single deployment runtimes like Thorntail, however this is a problem for containers like WildFly/JBoss EAP. Just to emphasize, the spec by now means mandates only a single deployment.

Configuration in the form of `io.smallrye.faulttolerance.globalThreadPoolSize` reintroduces the same problem where all deployments (1) share the same thread pool and (2) deployments cannot bring their own configuration.

**Comment by rhusar** [comment]
Looking at the code, this might be mostly a misnomer - its just a thread pool size used within a @Singleton which is going to be specific to the deployment - so not global. Also, I don't see anything statically shared, @michalszynkiewicz  can you confirm this was the intention?

**Comment by Ladicek** [comment]
I think we mostly avoid `static` variables, but not sure if we made any conscious effort towards that. It just came out of the design. We should make it an explicit goal, for sure.

**Comment by Ladicek** [comment]
One more thing, we should have probably called it "main threadpool" instead of "global", but renaming the config property would be a breaking change. (Which, at this point, probably wouldn't affect anyone, so we might still want to do it?)

**Comment by rhusar** [comment]
I intend to test this in the integration branch in WildFly and see where we stand and I would prefer renaming. 

Also, this can be renamed in a compatible way so thats not a peoblem.

**Comment by Ladicek** [comment]
Good point, we can still read the old config property if we don't find the new one. For some reason, I didn't think of that, shame on me :-)

**Comment by Ladicek** [comment]
Started working on this. Just rename `globalThreadPoolSize` to `mainThreadPoolSize` in a backwards-compatible way.

**Comment by Ladicek** [comment]
Done in #267.
