### ISSUE TITLE
dependency alignment for MicroProfile 3.3

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#186]
I wanted to release SRye FT 4.1.0 today, but I decided I'll wait with the release a bit so that we can align all the MP dependencies. That is:

- [x] MP Config 1.4
    - #181
- [x] SRye Config implementing MP Config 1.4
    - 1.6.0: #187
    - 1.6.1: #189
- [x] MP Metrics 2.3
    - #188
- [x] SRye Metrics implementing MP Metrics 2.3
    - 2.4.0: #193
- [x] we don't depend on other specs that change in MicroProfile 3.3 (Health, RestClient)

**Comment by Ladicek** [comment]
Finished!

**Comment by rhusar** [comment]
Neat!
