### ISSUE TITLE
durationUnit = ChronoUnit.SECONDS of @Retry is not implemented

### ISSUE THREAD

**Issue by yoshioterada** [smallrye/smallrye-fault-tolerance#206]
I evaluated the @Retry by using following code.
Then I noticed that the "durationUnit" is not implemented.

```
    @Retry(maxRetries = 6, durationUnit = ChronoUnit.SECONDS, delay = 10000)
    @Fallback(fallbackMethod = "fallback")
    @GET
    @Path("retry-timeout-fallback")
    public String checkTimeout() throws URISyntaxException {
        try {
            URI backendUri = new URI("http://localhost:8180/");
            HelloResourceInterface response = RestClientBuilder.newBuilder().baseUri(backendUri)
                    .build(HelloResourceInterface.class);
            return response.getHello();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            throw e;
        }
    }
```

If I invoked the above endpoint , following error was showed.
According to the log, about every 10 second error was showed.

```
2020-03-19 12:59:06,012 INFO  [stdout] (default task-1) RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
2020-03-19 12:59:15,900 INFO  [stdout] (default task-1) RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
2020-03-19 12:59:25,738 INFO  [stdout] (default task-1) RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
2020-03-19 12:59:35,744 INFO  [stdout] (default task-1) RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
2020-03-19 12:59:45,819 INFO  [stdout] (default task-1) RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8180 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

```

According to the source code of Delay and [ThreadSleepDelay](https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/ThreadSleepDelay.java), following was wrote.

```
public class ThreadSleepDelay implements Delay {
    private final long delayInMillis;
    private final Jitter jitter;

    public ThreadSleepDelay(long delayInMillis, Jitter jitter) {
        this.delayInMillis = Preconditions.check(delayInMillis, delayInMillis >= 0, "Delay must be >= 0");
        this.jitter = Preconditions.checkNotNull(jitter, "Jitter must be set");
    }

    @Override
    public void sleep() throws InterruptedException {
        long sleep = delayInMillis + jitter.generate();
        if (sleep > 0) {
            Thread.sleep(sleep);
        }
    }
}
```

And it seems that the "ChronoUnit" check is not implemented.
So as a result, every 10sec(10000mil) retry happen not 10000 sec.

**Comment by Ladicek** [comment]
We had an issue like this for circuit breaker, which was fixed in 4.1.1 (see https://github.com/smallrye/smallrye-fault-tolerance/commit/918dccf1468a106a5d659e0c5c1d44425bafaf0a). I'll check if that's the same case with retry. Thanks for the report!

**Comment by Ladicek** [comment]
No, that seems to be implemented correctly, on the first sight.

**Comment by Ladicek** [comment]
I know what's wrong, this: `@Retry(maxRetries = 6, durationUnit = ChronoUnit.SECONDS, delay = 10000)`. You're mixing `delay` and `durationUnit`. If you want to specify chrono unit for `delay`, you use `delayUnit`. If you want to specify chrono unit for `maxDuration`, you use `durationUnit`.

**Comment by yoshioterada** [comment]
I could understand the dependency but where does the specifications is wrote?
If it is possible,Could you let me know where is reference about the specifications ?

**Comment by rhusar** [comment]
@yoshioterada Here: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#retry

**Comment by rhusar** [comment]
So each delay/jitter/maxDuration has its own unit. I would have designed the spec differently, e.g. at least calling it "maxDurationUnit" and "jitterUnit" would be less confusing...

**Comment by Ladicek** [comment]
Agree @rhusar. Next MP Fault Tolerance release is 3.0 and some breaking changes are already planned. If you could file an issue with your suggestion, that would be great :-)

**Comment by yoshioterada** [comment]
Yes, if there is a strong dependency, I hope that the specification should write the dependencies (current specification is a little bit ambiguous). 
In my case, I used the IDE interpolation, thus I configured the miss combination.

**Comment by Ladicek** [comment]
I don't think the specification is ambiguous, the Javadoc is pretty clear in this regard. I agree the naming is inconsistent and can be improved, for sure.

**Comment by yoshioterada** [comment]
Thanks. I hope that it will be improved for all of the developers who use the MicroProfile.

**Comment by Ladicek** [comment]
Filed https://github.com/eclipse/microprofile-fault-tolerance/issues/524
