### ISSUE TITLE
Cannot implement custom TimeoutWatcher

### ISSUE THREAD

**Issue by davsclaus** [smallrye/smallrye-fault-tolerance#214]
The public interface `io.smallrye.faulttolerance.core.timeout.TimeoutWatcher` has API that are package private in scope and therefore you cannot implement a custom watcher.

```
import io.smallrye.faulttolerance.core.timeout.TimeoutExecution;
import io.smallrye.faulttolerance.core.timeout.TimeoutWatch;
```

These two classes are not public and they are referenced from the `TimeoutWatcher` api.

In Apache Camel we would like a custom watcher in our integration with this CB implementation.
https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-14179

We are using this version
```
        <dependency>
            <groupId>io.smallrye</groupId>
            <artifactId>smallrye-fault-tolerance</artifactId>
            <version>4.2.0</version>
        </dependency>
```

**Comment by Ladicek** [comment]
`io.smallrye.faulttolerance.core` is a private API. Noone should use it, it can break at any time. See https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/core/src/main/java/io/smallrye/faulttolerance/core/package-info.java

Now -- what is it exactly that you want to do?

**Comment by davsclaus** [comment]
Thanks @Ladicek 

We found an alternative which we could improve in camel-core instead. We wanted to control that cancel the future task should not allow interrupt (the value is hardcoded to true). So we just use the default watcher now.

You are welcome to close this ticket

**Comment by Ladicek** [comment]
OK, thanks.

I'll just point out again that if you're using the `io.smallrye.faulttolerance.core` classes directly, you _will_ see breaking changes without notice.

There's a discussion about providing pure-Java, no-CDI, APIs for all SmallRye projects. We will want to have one for SmallRye Fault Tolerance as well. But `io.smallrye.faulttolerance.core` is _not_ it, it will look differently (not yet sure how).

**Comment by davsclaus** [comment]
Thanks yeah Luca told me about the plain API smallrye effort (eg not tied to CDI as you say) and that sounds awesome. Love these small libraries you have built here.
