### ISSUE TITLE
support additional async return types

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#219]
We should support additional asynchronous return types, in addition to just `CompletionStage`. That is:

- Mutiny: `Uni`
- RxJava: `Single`, `Maybe`, `Completable`
- Reactor: `Mono`

We can probably ignore stream types (`Multi`, `Observable`/`Flowable`, `Flux`) for now.

**Comment by Ladicek** [comment]
See also https://github.com/smallrye/smallrye-fault-tolerance/pull/218#issuecomment-616513212

**Comment by schulzp** [comment]
Hi @Ladicek!

I'd highly appreciate support for `Uni` and the like. It would save us the `@Asynchronous` overhead as we're already using Vert.X' asynchronous web client. Is this part of any roadmap, already?

**Comment by Ladicek** [comment]
Hi @schulzp, I think what you're after is #218. This issue is just about allowing different return types for `@Asynchronous` methods. (Actually perhaps you want a combination of both :-) )

If you care about not having to use `@Asynchronous`, or more generally about its semantics of "always run this on an extra thread", you can comment on #218 and also on https://github.com/eclipse/microprofile-fault-tolerance/issues/533 -- hearing from community folks would be very good.

As for roadmap, unfortunately there's none at the moment, as I have very little time to spare on SmallRye Fault Tolerance :-(

**Comment by Ladicek** [comment]
Done in #310.
