### ISSUE TITLE
Feature request: Provide integration with smallrye-health for CircuitBreaker

### ISSUE THREAD

**Issue by andreas-eberle** [smallrye/smallrye-fault-tolerance#222]
I'm using `smallrye-fault-tolerance`'s `@CircuitBreaker` in a project to protect my database in case it is struggling. However, since my service cannot do its job when the database isn't there, I would like my readiness probe to fail. This is especially important in case only one pod has connection issues. Then the other pods could continue working and the pod with issues would be taken out of the load balancer. 

Therefore it would be great to have `smallrye-health` support for the `@CircuitBreaker` annotation. Since there are also use cases where you wouldn't want to have your readiness probes to fail, it would be good to have this feature configurable on the `@CircuitBreaker` annotaton. 

I could imagine two parameters `failReadinessWhenOpen:boolean` and `readinessProbeName:String`. With these, you could activate the readiness failing per annotation and also specify a readiness probe name to make visible which part of your application is causing the readiness to fail.

**Comment by Ladicek** [comment]
I'm not sure how I feel about that. For your particular usecase, I believe having a standalone health check for the database is a much better solution. It would also potentially react faster than a CB-based health check.

I'll leave this issue open in case someone can come up with a usecase that would be a good fit.

**Comment by andreas-eberle** [comment]
The database was only a simple example. The same issue is maybe more valid for external services. There, I cannot do a simple health check.

**Comment by rhusar** [comment]
👎 I don't think this is a good idea. If you want to implement such behavior, the intention is to implement a custom health check which consults the state of a circuit breaker. I could see how this could be an example somewhere, but not as a first-class configuration pattern. Moreover, this is not the intention of the CircuitBreaker to make entire service unavailable, but rather to fail fast and eventually open again for a particular code path.

**Comment by Ladicek** [comment]
For external services, you should pretty much always be able to implement a standalone health check.

I do feel like there is probably a good usecase for this, but can't come up with one myself, and don't see one in this discussion either.

**Comment by andreas-eberle** [comment]
> 
> 
> 👎 I don't think this is a good idea. If you want to implement such behavior, the intention is to implement a custom health check which consults the state of a circuit breaker. I could see how this could be an example somewhere, but not as a first-class configuration pattern. Moreover, this is not the intention of the CircuitBreaker to make entire service unavailable, but rather to fail fast and eventually open again for a particular code path.

How could I get the state of a cicuit breaker to use it for a health check?

**Comment by andreas-eberle** [comment]
> 
> 
> For external services, you should pretty much always be able to implement a standalone health check.
> 
> I do feel like there is probably a good usecase for this, but can't come up with one myself, and don't see one in this discussion either.

Unfortunately, this isn't always the case. Especially not if you don't own the service. Furthermore, a simple health check my still work but the calls you need might not. Nobody can guarantee you that the external service provider managed to do his health checks properly.

But the idea of this library (as far as I understood it) seems to be to build resilient services. If that is the case, I think this could be an important tool to improve the resilience of my service.

**Comment by Ladicek** [comment]
I don't think we understood each other. I'm saying, if your application consumes an external service, your application should have a health check that will verify availability of that external service, and that health check will contribute towards health (liveness or readiness) of your application. For sure you shouldn't rely on the external service doing anything.

**Comment by Ladicek** [comment]
And indeed it's currently not possible to access the CB state. I have filed that feature request a year ago :-) https://github.com/smallrye/smallrye-fault-tolerance/issues/69

**Comment by andreas-eberle** [comment]
Sure, but how should I be able to check the health of an external service, if it is e.g. only providing the productive calls and no dedicated health call? Furthermore, what if they have a weak health call which still succeeds although the calls I need fail?

**Comment by andreas-eberle** [comment]
I have at least one case where I only do a POST.

Anyways, even if I can do a get, nobody gurantees that the POST, PUT or DELETE call will work as well. We cannot even know if the calls go to the same service? The GET could be served by a CDN or a different server. I don't know, cannot know and don't want to know the internals of an external service. And who knows what the future will bring. If it is working now, it might not be working tomorrow.

Buy listening on the state of the circuit breaker, I get to know the actual truth. No assumptions have to be made. This way, the external service can be a black box. That's why I think this is exactly something this library should want to support. This makes it really resilient. 

I don't say this is what you always want to do! But I see that this has use cases, especially with external services. But also for internal services, I think it is no good idea to depend on assumptions you might be able to make today but can never be sure to work in the future. But making a service resilient is exactly about handling such corner cases.

**Comment by Ladicek** [comment]
In a similar style of argument, you can say that circuit breaker being open doesn't necessarily mean that the external service is down. The circuit breaker reacts to exceptions being thrown from your code, etc. etc. etc.

However, I think it's a valid usecase for providing access to the CB status. Since health checks are CDI beans, you can then implement the health check yourself.

**Comment by andreas-eberle** [comment]
So yes, if I would get the state, I could do it myself.

> In a similar style of argument, you can say that circuit breaker being open doesn't necessarily mean that the external service is down. The circuit breaker reacts to exceptions being thrown from your code, etc. etc. etc.

Right, it doesn't have to be down. If it's not and only one pod has an issue connecting to the service, it would be awesome to just take it out of the cluster with a readiness probe (the idea behind this ticket). And with the proposed addition to the annotation, I could configure if I want to use this specific circuit breaker for a readiness probe. I can do this per method, depending on how important this method is for my service. So I decide if this should take my pod of the balancer or not. In that regard it offers the possibility to easily get fine grained health checks. I might be fine if some calls of the external service are unreliable or always fail, but I might require some others.

**Comment by Ladicek** [comment]
It will be possible (soon) to observe circuit breaker state changes by listening to a CDI event (see #235). Since health check is a CDI bean, it can easily observe events. I'd welcome any comments on the PR.

**Comment by Ladicek** [comment]
I'm about to release 4.3.0, which will provide access to circuit breaker status.

I'm still not sure how I feel about using CB status to mark a service unhealthy -- because, as you say, the goal is "to build resilient services", which stay healthy in presence of failures, not go down. But in the end, you're the one building and running the app, so the tool is here for you to use.
