### ISSUE TITLE
Incorrect delay compare in RetryConfig validate method

### ISSUE THREAD

**Issue by klaasjan** [smallrye/smallrye-fault-tolerance#225]
See https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/config/RetryConfig.java#L74

At this spot, the comparison between delay and max duration does not work correctly if the units (delayUnit, durationUnit) are different and throws an exception with a correct configuration. (I tried with a duration of 10 seconds and a delay of 500 milliseconds; it incorrectly assumes 500ms is greater than 10 seconds and fails to initialize).

**Comment by Ladicek** [comment]
Nice finding, thanks!

**Comment by Ladicek** [comment]
Should be easy to fix. If you want to take a stab at it and submit a PR, that would be welcome!

**Comment by klaasjan** [comment]
You're welcome: https://github.com/smallrye/smallrye-fault-tolerance/pull/226

**Comment by Ladicek** [comment]
Thanks!
