### ISSUE TITLE
investigate whether we need to move circuit breaker from open to half-open asynchronously

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#249]
Currently, all circuit breaker state changes are synchronous -- that is, they only happen when some invocation occurs. If no invocation is thrown at the circuit breaker, it can't change state. This means that even if we configure the circuit breaker to transition from open to half-open after 5 seconds, if there's no invocation in 10 seconds, the circuit breaker will stay open for 10 seconds.

This doesn't have an effect on invocations themselves -- they are still processed correctly according to the circuit breaker rules. However, if users observe circuit breaker state changes, either directly (via the CDI event) or indirectly (via metrics), they will get wrong impression at least, and if they drive some decisions based on those data, then perhaps those decisions will be wrong.

Need to think about this.

**Comment by Ladicek** [comment]
Note to self: if we were to move circuit breaker from open to half-open asynchronously, we wouldn't be able to fire the state change event, because the event mechanism is currently bound to invocations (`InvocationContext` holds the callbacks). We'd probably need to add some form of global store of certain callbacks.

**Comment by linktech1** [comment]
Has there been a resolution for this? We need this transition to happen after the delay time without making a request.

**Comment by tbkahuna48** [comment]
We deploy to the Azure cloud and the liveness and readiness checks expect to be able to return a state other than OPEN. Currently they use Resilience4j which allows a setting at which time the breaker status will transition from OPEN to HALF-OPEN without another request. If the readiness fails (we report any thing but OPEN) the node is taken off line and can not be brought back without a successful readiness call. No transactions can get through until the pod is brought back up. So since a transaction is needed to shift to HALF-OPEN it will never come back up.

**Comment by Ladicek** [comment]
Understood, thank you all. I'll make this a higher priority.

That said, I would probably recommend against using circuit breaker status for health checks, because open circuit breaker shows a failure on the _other_ side (if used for guarding network calls).

**Comment by Ladicek** [comment]
I've fixed this and the fix will be part of SmallRye Fault Tolerance 5.6.0.

I'll just reiterate that I believe using circuit breaker state to drive health checks is a bad idea, because circuit breakers, when used as intended, don't tell anything about the "current" service -- they guard against failures of the "other" service.

If a health check is supposed to signal network failures (which is questionable in and of itself), it should be implemented independently.

**Comment by tbkahuna48** [comment]
Yes but we don't think a service is healthy if it can't call the back end services it needs to complete a request, at least those that are required.

**Comment by Ladicek** [comment]
I understand this is what people often do, but if not done carefully, it may easily lead to the entire system collapsing when some "key" backend service becomes unavailable. Fault tolerant systems should degrade gracefully, in my opinion.
