### ISSUE TITLE
Behavior of @Asynchronous Methods with @Retry on Exception

### ISSUE THREAD

**Issue by JRasteiro** [smallrye/smallrye-fault-tolerance#260]
When using the `@Retry` with specific exceptions annotation on `@Asyncrhonous` methods the retry behavior seems to be ignored.

For example something like:

```
    @Asynchronous
    @Retry(maxRetries = 4, retryOn={SomeException.class})
    @Fallback(fallbackMethod = "fallbackMethod")
    public CompletionStage<Void> someMethod() {
        return CompletableFuture.failedFuture(new SomeException("Something"));
    }
```

Would never retry and would immediately complete exceptionally.
The cause seems to be related with every exception "thrown" by the CS being wrapped in `CompletionException` and it being used to compare with the retryOn list instead of the exception's cause.

`CompletionStageRetry` using `Retry`'s implementation of `shouldAbortRetrying()`:
https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java#L82

which compares it directly at the retry list:
https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/Retry.java#L114

I guess the same issue happens with `abortOn` too.

**Comment by Ladicek** [comment]
I spent quite some effort making sure that we don't use `CompletionStage` in a way that leads to creating the `CompletionException`, because I find that exception wrapping quite sad.

Of course I might have missed some cases.

**Comment by Ladicek** [comment]
I have just translated your example into a test, inserted `System.out.println("!!!!!!!!!!!!!!!");` at the beginning of `someMethod`, and saw 5 lines full of exclamation marks. I tried with the 4.3.0 release and also on the `master` branch.

This suggests that the issue you observe is different. Can you please share a full (but minimal) reproducer?

**Comment by Ladicek** [comment]
I also tested with OpenJDK 8 and OpenJDK 11, works fine in both cases.

**Comment by Ladicek** [comment]
I've added the test to a branch here: https://github.com/Ladicek/smallrye-fault-tolerance/commits/issue-260

**Comment by JRasteiro** [comment]
Thanks for the quick reply!
I'll run the example on the branch and take a look at our usage to get a clearer view on what's happening. I'm using the 4.3.0 release with OpenJDK 11 as well.

**Comment by Ladicek** [comment]
Cool, please let me know what you find.

I can imagine one situation where this might happen: if the guarded method itself uses `CompletionStage` operators that wrap the original exception into a `CompletionException`. I'm not sure if we unwrap the exception in such case or not -- if not, that would lead to the behavior you describe.

**Comment by Ladicek** [comment]
My last comment seems to be correct. I've just replaced the method body with something like this:

```java
return completedFuture(null).handle((value, exception) -> {
    throw new SomeException();
});
```

and indeed there's no retry. This should be easy to fix.

**Comment by Ladicek** [comment]
Submitted a PR with a fix: #262.

**Comment by JRasteiro** [comment]
I poked around with the test example and indeed I couldn't replicate the issue as I was seeing it on my side.

However adding an extra `whenComplete()` would replicate the issue, even without throwing an exception.

```
    @Asynchronous
    @Retry(maxRetries = 4, retryOn={SomeException.class})
    @Fallback(fallbackMethod = "fallbackMethod")
    public CompletionStage<Void> someMethod() {
        return CompletableFuture.failedFuture(new SomeException("Something"))
                .whenComplete((o, ex) -> {
                    System.out.println("here!");
                });
    }
```

An example closer to the real case is something like:

```
@Asynchronous
@Retry(maxRetries = 4, retryOn = { WebSocketHandshakeException.class })
@Fallback(fallbackMethod = "fallbackMethod")
public CompletionStage<Void> someMethod() throws URISyntaxException {
        COUNTER.incrementAndGet();

        return HttpClient.newHttpClient()
            .newWebSocketBuilder()
            .buildAsync(new URI("ws://example.com"), new Listener() {})
            .thenApply(x -> null);
    }
```

However, removing the `thenApply()` and changing the method return type has the same issue.
So I'm guessing the buildAsync in this case is adding some extra steps to the handling of the result and is causing the issue. But I still don't see where the wrapping of a CompletionException is happening because of adding an `whenComplete()`.

**Comment by Ladicek** [comment]
There's a bunch of methods in `CompletableFuture` that, in an exceptional case, calls `completeThrowable`, which uses `encodeThrowable`, which wraps the exception into `CompletionException`. The `whenComplete` method is among them, as is `handle` and others. So the PR should fix the issue for you.
