### ISSUE TITLE
Allow use of either MP Metrics or Micrometer

### ISSUE THREAD

**Issue by ebullient** [smallrye/smallrye-fault-tolerance#265]
Allow smallrye-fault-tolerance to use either MP Metrics or Micrometer.

* Make MP Metrics an optional/compile dependency
* Add Micrometer as an optional/compile dependency

**Comment by ebullient** [comment]
Done after/atop #264

**Comment by Ladicek** [comment]
Does the issue express an intent to work on $SUBJ, or is it just an ask for me to do it?

(If the former, please feel free to ping me any time, but I see you already noticed #264, which largely centralized all the metrics to a few isolated classes. I don't know anything about Micrometer, but I'd naively expect that a new implementation of `MetricsRecorder` should be enough. Plus a small modification to `MetricsProvider.create`.)

**Comment by ebullient** [comment]
I will work on it. ;) No ask from you.

**Comment by Ladicek** [comment]
In that case please use the `next` branch, it has the metrics refactoring and a few other improvements already. I keep it separate from `master` in case we need to do another release of SRye FT before MP FT 3.0 is done.

**Comment by ebullient** [comment]
I will start there, and then sort out with Ken if we need it on Master for Quarkus earlier

**Comment by kenfinnigan** [comment]
@Ladicek have we reached a point where "next" can become master?

**Comment by Ladicek** [comment]
`next` implements MP Fault Tolerance 3.0, so until MP FT 3.0 is released, it needs to stay `next`. Nothing prevents submitting PRs against it, though.

**Comment by Ladicek** [comment]
Note to self: need to consider https://github.com/quarkusio/quarkus/issues/24597
