### ISSUE TITLE
Circuitbreaker not opening with certain parameters with fallback method

### ISSUE THREAD

**Issue by dvddhln** [smallrye/smallrye-fault-tolerance#28]
Hi,
I am trying to use the `CircuitBreaker` annotation with following parameters
```
@Fallback(fallbackMethod = "handleLoginFailure")
@CircuitBreaker(successThreshold = 1,requestVolumeThreshold = 2, failureRatio = 0.5,
delay = 15, failOn = {Exception.class}, delayUnit = ChronoUnit.SECONDS)
```
I make two sucessfull requests as expected and then it breaks as expected on the first unsuccessful request, but the subsequent request passes through as if it was closed. Am I missing something in the configuration or is this expected behaviour? Should'nt the delay be active now and the fallback method should be handling the subsequent requests during the duration of the delay?

/David

**Comment by mkouba** [comment]
Hi @dvddhln, do you have a minimal reproducer app we can look at? And yes, an open circuit should not attempt to pass a request before the delay time is reached.

**Comment by dvddhln** [comment]
Hi @mkouba 
Here is an attempt to reproduce the issue https://github.com/dvddhln/circuit-breaker-issue
Not sure I am doing anything wrong though..

**Comment by mkouba** [comment]
Ok, so I think that the test is wrong. The FT operation is defined like this:  
```java
 @Fallback(fallbackMethod = "operationFailure")
 @CircuitBreaker(successThreshold = 1, requestVolumeThreshold = 2, failureRatio = 0.5, delay = 15, failOn = {RuntimeException.class}, delayUnit = ChronoUnit.SECONDS)
  public String operation() { }
```
But the `TestCircuit` only makes 4 requests. First two are OK. Then one fails - but the circuit breaker is not open yet as it waits for the next request to pass the threshold defined in `requestVolumeThreshold`.

If you change the code to something like:
```java
 @Fallback(fallbackMethod = "operationFailure")
 @CircuitBreaker(successThreshold = 1, requestVolumeThreshold = 3, failureRatio = 0.3, delay = 15, failOn = {RuntimeException.class}, delayUnit = ChronoUnit.SECONDS)
  public String operation() { }
```
The test passes because `testGetWithFailureFirstExpectedFallback()` closes the circuit breaker.

**Comment by dvddhln** [comment]
Thanks, I see your suggestion works. But how would I write the annotation if I wanted to open the circuit in the first occurrence of a failure, and then it have it open for the delay period, until the next request arrives? Perhaps my case is not feasible?

**Comment by mkouba** [comment]
`@CircuitBreaker(requestVolumeThreshold = 1, failureRatio = 0.5, delay = 15, delayUnit = ChronoUnit.SECONDS)` should work.

**Comment by dvddhln** [comment]
Then the last test(4) fails, is this expected?

**Comment by mkouba** [comment]
`SynchronousCircuitBreaker` is not resetting the counters when the `requestVolumeThreshold` is reached unless the status is changed. As a result, a rolling window where all requests succeed affects the computation of the next window.

**Comment by dvddhln** [comment]
Thanks for looking into this @mkouba
