### ISSUE TITLE
Update MP Metrics to 3.0

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-fault-tolerance#283]
To fully support MicroProfile 4.0, we will need a release of FT that is compiled against MP Metrics 3.0, because there are some changes from 2.3 that affect binary backward compatibility.

**Comment by Ladicek** [comment]
OK, so, the SmallRye Fault Tolerance release that is supposed to implement MicroProfile Fault Tolerance 3.0 (which is what MicroProfile 4.0 will include) needs to be compiled against MicroProfile Metrics 3.0. Do I understand that correctly?

If so, what will be the SmallRye Metrics version that implements MicroProfile Metrics 3.0?

(FTR, I'm still contemplating whether the SmallRye Fault Tolerance version that implements MicroProfile Fault Tolerance 3.0 should be 4.4 or 5.0. The only breaking change we do is metrics :-) )

**Comment by jmartisk** [comment]
> OK, so, the SmallRye Fault Tolerance release that is supposed to implement MicroProfile Fault Tolerance 3.0 (which is what MicroProfile 4.0 will include) needs to be compiled against MicroProfile Metrics 3.0. Do I understand that correctly?

Yes, exactly!

> If so, what will be the SmallRye Metrics version that implements MicroProfile Metrics 3.0?

3.0.0. Maybe I could release 3.0.0-RC1 for now if you'd prefer to do a prelimimary upgrade now, otherwise my release plan is to do 3.0.0.Final along with MP 4.0 release.

> 
>  The only breaking change we do is metrics :-) )

That's unfortunate, sorry for adding more work to you :)

**Comment by Ladicek** [comment]
I don't need an RC, no, just wanted to check if I understand correctly. Thanks!

**Comment by Ladicek** [comment]
Note to self: when updating to MP Metrics 3.0, we no longer have to depend on SmallRye Metrics API.

**Comment by Ladicek** [comment]
Done in #332.
