### ISSUE TITLE
rework the thread pool integration

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#287]
Right now, SmallRye Fault Tolerance insists on creating its own thread pools, which is a waste of resources. There's an integration point (`ExecutorFactory`) which integrators can provide, but it also encourages them to create new thread pools.

We need to rework this. Ideally, SmallRye Fault Tolerance would only use _one_ thread pool, and let the integrator provide it.

Related: #209 #278

**Comment by Ladicek** [comment]
Done in #279.

**Comment by rhusar** [comment]
So we went from CDI to ServiceLoader back to CDI, what a circle of life!

**Comment by Ladicek** [comment]
I didn't like the service loader, but it made a bit of sense when the interface had 3 methods for 3 different kinds of thread pools. Now, we only need 1 thread pool for everything, and the integration ideally shouldn't create it but provide an existing one. CDI seems to make that a bit easier.

But I agree it's quite an irony :-)
