### ISSUE TITLE
Add support for Uni

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-fault-tolerance#351]
It would be great to have the support for `Uni` in addition to `CompletionStage`.
Such support could potentially be implemented in its own module.

**Comment by Ladicek** [comment]
Closing, as this is a dulicate of #219. FYI, it's implemented in 5.0.0, which should be released any day now (did an RC2 yesterday).

**Comment by cescoffier** [comment]
Oh pretty cool!
