### ISSUE TITLE
Jakarta EE bootstrap support

### ISSUE THREAD

**Issue by sergey-morenets** [smallrye/smallrye-fault-tolerance#369]
Hi

I asked more specific question for another project:
https://github.com/smallrye/smallrye-config/issues/502

And another questions is more general. Can we apply fault tolerance strategies (retry, timeout) in declarative or programmatic way  during Jakarta EE container bootstrap?

**Comment by Ladicek** [comment]
There's no programmatic API (yet). When it comes to declarative API, that is, the MP Fault Tolerance annotations, they are regular CDI interceptor binding annotations, so they can be used whenever CDI can be used. What that means to Jakarta EE container bootstrap, I have no idea, and I guess it's implementation dependent. More details could let me answer your questions in more detail.

**Comment by sergey-morenets** [comment]
> 
> 
> There's no programmatic API (yet). When it comes to declarative API, that is, the MP Fault Tolerance annotations, they are regular CDI interceptor binding annotations, so they can be used whenever CDI can be used. What that means to Jakarta EE container bootstrap, I have no idea, and I guess it's implementation dependent. More details could let me answer the question better.

The simple examples is Jakarta EE container tries to create a CDI bean and fails because this bean can't establish connection yet. So I would like to add retry/timeout strategies for this process(bean creation) and give one more chance to success.

**Comment by Ladicek** [comment]
Alright so you actually meant application bootstrap, or (since beans can be created lazily) even bean creation specifically. I'm afraid that's not possible directly. How does the code that "establishes connection" look like? If that's yet another CDI bean, then you might be able to use fault tolerance on that CDI bean.

For anything more complex, we would need the programmatic API.

**Comment by sergey-morenets** [comment]
> 
> 
> Alright so you actually meant application bootstrap, or (since beans can be created lazily) even bean creation specifically. I'm afraid that's not possible directly. How does the code that "establishes connection" look like? If that's yet another CDI bean, then you might be able to use fault tolerance on that CDI bean.
> 
> For anything more complex, we would need the programmatic API.

Thank you. Do you have any plans to design programmatic API ?

**Comment by Ladicek** [comment]
Nothing too specific, but I've opened #370, so you can subscribe to that.

**Comment by Ladicek** [comment]
Closing, #370 can be tracked instead.
