### ISSUE TITLE
Unit test does not trigger the fallback methods

### ISSUE THREAD

**Issue by vvavepacket** [smallrye/smallrye-fault-tolerance#371]
Why is that when I have a unit test and when a method that is annotated with @Fallback annotation, it appears that the fallback method does not get called during unit test?

Whats happening is the exception is still thrown

**Comment by Ladicek** [comment]
Sorry, you didn't provide any kind of detail that would allow me to answer your question. I can only guess: `@Fallback`, as well as all other MicroProfile Fault Tolerance annotations, is an _interceptor binding_ annotation, and hence can only be used on CDI beans. It seems you annotate a method on the test class, which is probably not a CDI bean, and hence the annotation is meaningless.

**Comment by Ladicek** [comment]
No info provided, closing.
