### ISSUE TITLE
a lot of tests fail on JDK 17-ea+21

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#412]
When building SmallRye Fault Tolerance with JDK 17-ea+21, a lot of tests fail with the following error:

```
java.lang.reflect.GenericSignatureFormatError:
Signature Parse error: Expected Field Type Signature
        Remaining input: java.time.temporal.ChronoUnit
```

This is ultimately caused by https://github.com/jbossas/jboss-classfilewriter/issues/24 and there's a fix: https://github.com/jbossas/jboss-classfilewriter/pull/15

When JBoss Class File Writer is released with the fix and Weld updates to it, the issue will be fixed simply by updating Weld.

**Comment by bstansberry** [comment]
Thanks so much @Ladicek -- I was seeing these testing WildFly and by luck I just read your diagnosis here. :)

**Comment by bstansberry** [comment]
"These" meaning that problem in general, not just with Smallrye FT.

**Comment by Ladicek** [comment]
Weld 3.1.8.Final has a dependency on JBoss Class File Writer 1.2.5.Final, which includes the fix. Updating Weld should do the trick (in SmallRye Fault Tolerance, that is).
