### ISSUE TITLE
Inability to define Fallback with FallbackHandler on void methods

### ISSUE THREAD

**Issue by michalovjan** [smallrye/smallrye-fault-tolerance#492]
Currently if you define `@Fallback` with your own class implementing a `FallbackHandler<TYPE>` on a method that returns void you will fail on build time validation with `fallback handler's type class <TYPE> is not the same as method's return type` (`<TYPEs>` tried were `Void.class`, `Object.class` or NO-TYPE).

**Comment by Ladicek** [comment]
Same thing also happens for primitive types.

The best solution probably is to expect `FallbackHandler` to use the boxed variant of the type, so for `void`, it should be `FallbackHandler<Void>`, while for e.g. `int`, it should be `FallbackHandler<Integer>`.
