### ISSUE TITLE
CircuitBreaker/Fallback/Retry could/should inspect the exception cause chain

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#524]
The `@CircuitBreaker`, `@Fallback` and `@Retry` fault tolerance strategies have configuration properties to treat certain exceptions as failures and others as successes. The strategies themselves only inspect the actual exception that was thrown. Sometimes, relatively often in certain usecases, exceptions are wrapped in a wrapper exception and the actual exception the user wants to decide on is only present in the cause chain.

I think it would make sense to just always inspect the cause chain of the exception, perhaps even the set of suppressed exception, though that probably isn't what the specification says. (There is likely no TCK for this, but I'm not 100% sure.)

Another way would be to add an option to enable such behavior. When a method has more than 1 fault tolerance annotation, it's probably fine to enable the cause checking for all fault tolerance strategies on that method (which would lead to adding one annotation). It might even be enough to just have a global switch for the entire application (which would lead to adding one config property).

**Comment by Ladicek** [comment]
Yet another option would be to always inspect the cause chain, but only in the spec non-compatible mode (which is on by default in Quarkus).

**Comment by Ladicek** [comment]
Done in #546.

**Comment by fwippe** [comment]
Any chance of bumping SmallRye Fault-Tolerance to 5.2.2 for Quarkus 2.7 to use that feature?

**Comment by edeandrea** [comment]
I guess this would be easier if the clients didn't just use an "uber" exception type. Coming from things like Spring where there is a dedicated exception class for each http status would make this trivial, but you can't change your clients :)

**Comment by Ladicek** [comment]
JAX-RS has exception types for the most important HTTP status codes, I have no idea why RESTEasy / RESTEasy Reactive doesn't throw them :-)

**Comment by AndreasPetersen** [comment]
Not sure if it's a Quarkus of Smallrye issue, but this doesn't seem to work in Quarkus. I've updated the relevant Quarkus issue with a reproducer https://github.com/quarkusio/quarkus/issues/22832.
