### ISSUE TITLE
Unable to have logs on faulttolerance operations

### ISSUE THREAD

**Issue by manofthepeace** [smallrye/smallrye-fault-tolerance#641]
I am using SR FT in a quarkus project. I'd like to be able to log what is going on where I have faulttolerance annotations.

Basic example, I would like to just basically log on retry, which api got retried, and maybe some context, if any. At the moment I do not know how to have that.

I tried few things without success.

1. I tried to put a decorator on some Ft bean, but ultimately I got nowhere with that. Or the decorator would not get called, or I would get a class not found exception on my own decorator itself (really dont understand that one..)
2. I tried observing CDI Events, as I saw the fireEvents in the retry class, but they dont seem to be cdi events, as I am not observing anything (or am I misusing it?)
3. Enabled `io.smallrye.faulttolerance.core.retry.Retry` to trace level, but it's too much and not enough at the same time, as I do not see the actual bean/beanmethod that got retried.

We have a lot of restClient in our project and use the `@Retry` a lot, but when things fails on the remotes, we cannot troubleshot at all at the moment, as we do not know if our app retried or not/how many times, or what have happened. So having the possibility to be able to have basic logs would be great, would be nice to manage the logs ourselves as well, via cdi events maybe, or a decorator.

**Comment by Ladicek** [comment]
I'd generally suggest to put logs into the annotated method, as Fault Tolerance has almost no interesting application-specific information to log. In case of RestClient methods, that gets a little clunky -- you basically have to wrap the RestClient interface by a service class, put FT annotations on _that_ class, and route all invocations through it. But it's also the easiest thing possible.

Alternatively, it should be possible (though I don't recall how off the top of my head) to enable logging of the RestClient invocations themselves.

Also, fault tolerance emits metrics (though [Micrometer support](#265) is unfortunately still not there), which are pretty granular. To observe retries, that's probably the best way.

**Comment by manofthepeace** [comment]
Thanks for your time and your reply.

I do understand that Fault Tolerance does not have much info of the application itself. In general I think just the class/methodName would be enough at least we know what calls where made by FT and in which case ( the ones in the RetryEvents class for example)

I already have a sort of service wrapping the RestClient, the retries are not on that service though, but I am unsure how to differentiate an actual call to the service, or a call from Fault Tolerance/retried. As our app can control via configuration the retries properties (including the abortOn/retryOn) it would really be useful to be able when we receive a log from outside seeing something like "ah ok FT retried twice in 10 sec and then that's why it failed with that message". In our current case we can only assume something happened.

In the metrics, it's a bit hard to actually track down, when we have the current flow with timestamps in the logs.

I understand it might be a special case, I have tons of those :) but I think it would be nice to be able to track what is going on via logs. In fact would be nice if the fireEvents I can see in the retry class could send actual CDI events with super basic info.

**Comment by Ladicek** [comment]
Okay, I just realized that Fault Tolerance actually _does_ have the application-specific information you're after -- each fault tolerance strategy has a `description`, which in case of the declarative API is `fully.qualified.name.of.TheClass#theMethodName`. It should be rather straightforward to add that into the log message.

Also, I always intended to promote some of the trace-level messages to the debug level, for this exact use case, but never got to it. Sounds like a good time :-)

**Comment by Ladicek** [comment]
BTW it would be interesting to know which log messages you'd consider debug-level worthy, and which you'd rather keep on the trace level. It seems obvious for retry, but not so much for other fault tolerance strategies.

**Comment by Ladicek** [comment]
Here's an attempted fix: #642 If you could take a look and let me know if that seems enough for you, that would be great :-)

**Comment by manofthepeace** [comment]
I reviewed the PR and it looks great, that's pretty much what I would expect as debug. My app being a cli app I am not using many other FT annotation, only `Fallback` and `Retry`. I can doublecheck what fallback prints as debug/trace, but I must say this is much easier to know what happens in case of fallback, since it calls a totaly seperate methos, which we cal, and already, log int. In the case of Retry it was basically not printing anything debug IIRC, so I think having basic info like the PR does will be really beneficial!

One comment maybe if I may, in the PR I see the debug + trace back to back. usually the trace is a log with more informations, but in this case it has less. So if I put my app at trace level, I will have somewhat duplicated logs that says the same thing, a little differently with the debug that as actually the description, and the trace that repeats the debug log without the description. I think they could be dropped?

**Comment by stephan-strate** [comment]
I would like to pick up on this.
You have added some amazing log statements for debugging. I would argue that these statements are also interesting for production usage (so info or warn level). Why? Eg. `Retry` in its nature can occur from runtime problems, external service not reachable, flicker, ... So having sophisticated logging for it, can be crucial.
I understand that not everyone wants to have these log statements enabled by default. My proposal would be to have some code-level option configure the logging behaviour. I thought of something like an annotation `Logged` or parameter of the existing annotations.

The workaround now would be to enable debug logging for faulttolerance specific packages. That works, but would come with some disadvantages. You could only configure its globally for all annotations, it could be filtered by some log aggregation tools as its on debug level, ...

What do you think?

Note: I opened a pull request #683 to add some more information to the `Retry` and `Timeout` logging.

**Comment by Ladicek** [comment]
You should be able to configure your logging backend to do this for you. The log messages have enough context for you to be able to select those that are of interest. If you use Quarkus, the logging backend is most likely JBoss LogManager, which is based on JUL, so you can for example provide a `java.util.logging.Filter` (which, in addition to returning `true` or `false`, can possibly even alter the log level of significant log messages).

**Comment by manofthepeace** [comment]
I do not think this is possible at the moment see https://github.com/quarkusio/quarkus/issues/25981. Unless I am not looking at the right thing. I did try but I am unsure how to register my filter with the logmanager.

**Comment by Ladicek** [comment]
Ouch, I didn't know that. I know Quarkus uses a log filter internally, so I thought there's a way to register a custom one too. Did you try simply obtaining the `Logger` for given category and calling `setFilter` on it? (`Logger.getLogger("io.smallrye.faulttolerance.xxx").setFilter(new MyFilter());`) It might just work.

**Comment by stephan-strate** [comment]
You can actually change the log level for an package like so: `quarkus.log.category."io.smallrye.faulttolerance".level=DEBUG`.

But I want to still argue, that these information are not debug level. These information are crucial information of runtime problems. And you usually do not have debug level activated on a production build.

**Comment by manofthepeace** [comment]
I already have `quarkus.log.category."io.smallrye.faulttolerance.retry".level=DEBUG` for my production application. I also think warn would be better in general. I will try what @Ladicek  proposed above. If that works I would think its could enough in a way. 

If they get chaned to warn and people really dont want them at least they can use `quarkus.log.category."io.smallrye.faulttolerance.retry".level=INFO` which seems like a good workaround if some think it's too much so I do not think it would ultimately hurt to have them log in normal cases.

**Comment by Ladicek** [comment]
I believe that configuration sets the minimum level that will be logged for that category. So if you want to see those debug messages, you need to keep that on `DEBUG`.

I understand your concern about detecting runtime problems -- that's why we emit fairly detailed metrics. I hesitate to promote these log messages to INFO (or even WARN), because if you use a fault tolerance annotation, the fact that a fault tolerance behavior happens is not an unexpected thing. We also generally strive to avoid log pollution. I'm all for being able to customize that logging, but there can only be one default.

**Comment by manofthepeace** [comment]
> Did you try simply obtaining the Logger for given category and calling setFilter on it? (Logger.getLogger("io.smallrye.faulttolerance.xxx").setFilter(new MyFilter());) It might just work.

This did not work. I have added it to a `@Startup` singleton bean. I have a breakpoint in the filter and it never gets executed.

**Comment by Ladicek** [comment]
> I have added it to a `@Startup` singleton bean.

You mean into a `@PostConstruct` method of a `@Startup @Singleton` bean?

**Comment by manofthepeace** [comment]
I tried in both the constructor and the postconstruct. just for completeness

This is the line `Logger.getLogger("io.smallrye.faulttolerance.retry").setFilter(new LoggingFilter());`

The LoggingFilter is the following;

```
public class LoggingFilter implements Filter {

    @Override
    public boolean isLoggable(LogRecord record) {
        if (record.getLoggerName().equals("io.smallrye.faulttolerance.core.retry")) {
            record.setLevel(Level.WARNING);
        }
        return true;
    }
}
```

I have a breakpoint on the if which I never reach.

**Comment by Ladicek** [comment]
I think you made a typo in the category name in `Logger.getLogger("io.smallrye.faulttolerance.retry")`. The `isLoggable` method seems to have the category name correct.

**Comment by manofthepeace** [comment]
yes ok it does work. Sorry I just copied from your comment and changed `xxx` to `retry`. Severe case of Mondays.

I tried in both constructor and postconstruct and it works;

2022-07-25 14:53:33,415 WARNING [io.sma.fau.cor.retry] (vert.x-eventloop-thread-8) org.acme.client$$CDIWrapper#login invocation failed, retrying

**Comment by Ladicek** [comment]
Great, thanks for confirmation!
