### ISSUE TITLE
`circuitbreaker.callsFailed.total` metric incremented if an exception is thrown, even if it isn't present in `failOn`

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#66]
If I have a `@CircuitBreaker(failOn = {IllegalArgumentException.class})` method and e.g. `IllegalStateException` is thrown, the `circuitbreaker.callsFailed.total` metrics currently gets incremented. It shouldn't be; instead, what should be incremented is `circuitbreaker.callsSucceeded.total`.

The MP Fault Tolerance spec is a little vague in this regard:

1. `circuitbreaker.callsSucceeded.total` is defined as "Number of calls allowed to run by the circuit breaker that _returned successfully_"
1. `circuitbreaker.callsFailed.total` is defined as "Number of calls allowed to run by the circuit breaker that then failed"
1. the `@CircuitBreaker` javadoc says "A method call will be considered a failure if it throws an exception and the type of that exception is assignable to any of the types listed in `failOn`."

From item 1 follows that in case of any exception, it should be the `circuitbreaker.callsFailed.total` metric that is incremented, because throwing an exception isn't a "successful return". However, from items 2+3 follows that it should be `circuitbreaker.callsSucceeded.total`.

The TCK of course doesn't test this. I'm going to file an MP Fault Tolerance issue for clarification, but my opinion is that the 2nd interpretation is correct, because that's how everything else in the circuit breaker works. Fix in SmallRye FT is pretty straightforward. 

FTR, this was originally filed as https://issues.jboss.org/browse/THORN-2361

**Comment by velias** [comment]
From the point of final app operation I agree that 2nd interpretation is correct. From this point of view, metrics are there to allow operator's insight into what is going on in the app, so they have to be aligned with real functionality of the Circuit Breaker component.
Thanks for pushing this problem to be patched.

**Comment by Ladicek** [comment]
Submitted https://github.com/eclipse/microprofile-fault-tolerance/issues/419 for spec clarification.

**Comment by Ladicek** [comment]
Draft PR: #67

**Comment by Ladicek** [comment]
It was agreed on the MP FT call yesterday that my 2nd interpretation is correct, here's a PR to fix the MP FT spec and add a TCK test: https://github.com/eclipse/microprofile-fault-tolerance/pull/421

**Comment by Ladicek** [comment]
PR is now ready for review: #67.
