### ISSUE TITLE
provide a way to obtain current circuit breaker status

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-fault-tolerance#69]
MicroProfile Fault Tolerance doesn't provide a portable way to get the current circuit breaker status. It's not even possible to add a metric for this purpose, because metrics can only be numbers (at least in SmallRye Metrics).

We should add some way of accessing current state of some circuit breaker, something like

```java
@Inject
@SmallRyeCircuitBreaker("com.example.myapp.feature.SomeClass.someMethod")
Supplier<String> circuitBreakerStatus;
```

(Just a throwaway idea, better API certainly exists.)

Without this, we can't fix https://issues.jboss.org/browse/THORN-1997 (= use MP Fault Tolerance in the circuit breaker booster, instead of Hystrix).

**Comment by Ladicek** [comment]
CC @michalszynkiewicz @mkouba

**Comment by mkouba** [comment]
Well, `com.example.myapp.feature.SomeClass.someMethod` cannot be used as a circuit breaker id - it's not unique, you need to include param types too. 

Right now, you could do 
```java
Method method = null; // TODO lookup the method
HystrixCircuitBreaker circuitBreaker = HystrixCircuitBreaker.Factory.getInstance(HystrixCommandKey.Factory.asKey(SimpleCommand.getCommandKey(method)));
```
But it's really ugly and Hystrix-specific.

So I like the idea of injecting some CB status abstraction but we would have to allow the user to specify a unique CB id first. Otherwise, it's unusable. Maybe just re-use `@SmallRyeCircuitBreaker("com.example.myapp.feature.SomeClass.someMethod")`?

**Comment by Ladicek** [comment]
Aha, makes sense. This

```java
@CircuitBreaker
@SmallRyeCircuitBreaker("my.circuit.breaker.id")
public String myServiceMethod() { ... }
```

would define an ID for the circuit breaker, and that could be used later for injecting status information:

```java
@Inject
@SmallRyeCircuitBreaker("my.circuit.breaker.id")
CircuitBreakerStatus cb;
```

At this point, I wonder if we should instead use `@Named`? I know it has some weird consequences, so probably not?

Anyway, thanks for pointing out that I can lookup the status from Hystrix for now, I'll take a look at doing that.

**Comment by Ladicek** [comment]
Ah one more point: the MP FT `@CircuitBreaker` annotation can be placed on a type, in which case it applies to all methods. Placing a `@SmallRyeCircuitBreaker` annotation on a type wouldn't be enough to define an ID for each circuit breaker, so perhaps we'd have to limit the annotation only to methods?

**Comment by mkouba** [comment]
> I wonder if we should instead use @Named?

Well, I wouldn't do this. In CDI `@Named` beans are automatically exposed through EL. Also there are some restrictions on the `@Named#value()`, the use of `@Named` as an injection point qualifier is not recommended, etc.

> so perhaps we'd have to limit the annotation only to methods?

Yes, makes sense.

**Comment by Ladicek** [comment]
Thanks @mkouba! I'll see what I can do about this, probably give it an hour or two today and if not, then it will have to wait :-)

**Comment by davsclaus** [comment]
At Apache Camel we would also like to be able to get the state of the CB
https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-14179

We have this information for our other implementations hystrix and resilience4j. 

The metrics reporter dont either seems to be fully capable of this, it does seem to have an event for close to open, but not for all state changes (half open etc).

**Comment by davsclaus** [comment]
You may be able via reflection to get the State field but that is an ugly hack, and wont work with native graalvm compiled etc and its not something we would like to use as workaround.

**Comment by Ladicek** [comment]
I started looking into this and decided to use CDI events. Whenever the circuit breaker changes state, we'll fire an event that will contain the bean class (`java.lang.Class`), the method (`java.lang.reflect.Method`), and the target state (simple enum).
