### ISSUE TITLE
Observability of Circuit breakers: expose current state of circuit breakers

### ISSUE THREAD

**Issue by turing85** [smallrye/smallrye-fault-tolerance#735]
The current state of circuit breakers is not exposed through metrics. It would be favorable to expose the current state of circuit breakers through metrics to, for example, configure monitoring and alerting on this metric.

Imlementation ideas:
- create one gauge value per breaker, with possible values `0`, `1`, `2`, encoding the states `closed`, `half-open` and `open`
- create one gauges per breaker and state, set the gauge representing the current state to `1`, the others to `0`
- create one value per breaker with tags encoding the state, as outlined [here](https://github.com/micrometer-metrics/micrometer/issues/1033#issuecomment-442965567).

**Comment by Ladicek** [comment]
I'll implement this using the 3rd option: 1 gauge (`ft.circuitbreaker.state.current`) with tags that specify 1. the method name, 2. the state name (`closed`, `open`, `halfOpen`). The value of the gauge will be 1 if the corresponding circuit breaker is "currently" in given state, and 0 otherwise.
