### ISSUE TITLE
Align MP Config spec and impl usage

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-fault-tolerance#8]
Currently the MP Config spec 1.2.1 is included, but SmallRye Config 1.3.0 as the impl which is based on MP Config 1.3

**Comment by mkouba** [comment]
Well, `smallrye-config` is only used for testing. TBH I'm a bit lost in all those MP versions and given that APIs are allowed to break compatibility it's not clear to me which version should we actually use for `smallrye-fault-tolerance` implementing MP FT 1.0. 

MP FT 1.0 was introduced in MP 1.2 with MP Config 1.1. SmallRye is currently MP 1.3 (Config 1.2) and 1.4 (Config 1.3).

In theory, if we don't need any Config 1.1+ feature and the compatibility is reained we could stay using Config 1.1 API. That would be the strategy I would expect...

**Comment by kenfinnigan** [comment]
If MP Config is purely used for testing, and not in the implementation, then maybe the API version/dependency should be removed and just the impl added to test scope?

**Comment by mkouba** [comment]
> If MP Config is purely used for testing...

It is not - `smallrye-fault-tolerance` makes use of MP Config API. But I believe it does not make sense to depend on a specific impl unless really needed, i.e. MP Config API is a compile dependency and `smallrye-config` is purely used for testing.

> and just the impl added to test scope?

It is: https://github.com/smallrye/smallrye-fault-tolerance/blob/master/pom.xml#L162

**Comment by kenfinnigan** [comment]
Ok, I think that's where I was getting confused as to why the API and impl were pulling different versions.

Maybe just a note in the pom about that distinction is sufficient
