### ISSUE TITLE
Unable to Set Circuit Breaker name at Runtime

### ISSUE THREAD

**Issue by yogeshn** [smallrye/smallrye-fault-tolerance#810]
I wanted to create a circuit breaker with a name that can be set at runtime. Is there a Builder which I use to set circuitbreaker name instead of using annotation?
```
@CircuitBreaker(requestVolumeThreshold = 4, failureRatio = 0.5, delay = 1000)
@CircuitBreakerName("#{hostUrl}")
public Uni<Response> get(HttpHeaders headers, String requestUri, URI hostUrl) throws Exception {
// Some logic
}
```

**Comment by Ladicek** [comment]
I'd advise against using circuit breakers for readiness, as they -- if used for guarding network interactions -- do approximate the state of the _other_ application, _not_ the "current" one.

Other than that, the programmatic API should be exactly what you need. I'm gonna close this issue, please feel free to reopen (or open another one) if you have any issues.
