### ISSUE TITLE
Integrate programmatic API with metrics

### ISSUE THREAD

**Issue by ranjanashish** [smallrye/smallrye-fault-tolerance#841]
Hi, I am using SmallRye Fault Tolerance in a Quarkus project. This is a request to integrate programmatic API of SmallRye Fault Tolerance with metrics.

**Comment by Ladicek** [comment]
Understood. This will happen eventually, but is not high on my priority list.

**Comment by magicprinc** [comment]
See also https://github.com/smallrye/smallrye-fault-tolerance/issues/919

+ grafana_dashboard.json would be great :-)

**Comment by Ladicek** [comment]
I have an example Grafana dashboard for the fault tolerance metrics here: https://github.com/Ladicek/fault-tolerance-demo It is heavily based on the OpenLiberty MP Fault Tolerance Grafana dashboard, so kudos to them!
