### ISSUE TITLE
Fault Tolerance Standalone customization concept

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#905]
What do you think about such a straightforward and uncomplicated way of customization (Let users integrate their own thread pool and Timer implementations)

https://github.com/magicprinc/smallrye-fault-tolerance/commits/feature/easy-customization

@Ladicek After your [recommendation](https://github.com/smallrye/smallrye-mutiny/issues/1408) I've started  using this project. Thank You!

**Comment by Ladicek** [comment]
Something like that would make sense, yes. I think I'd prefer a `ServiceLoader`-based solution, but yes, in principle, this is good.

**Comment by Ladicek** [comment]
One thing I'd like to ask about: why do you need to customize the timer creation function? I'd probably be reluctant to allow that, because the timer implementation is critical to the inner working of some fault tolerance strategies.

The executor, sure -- I just left a TODO for that, because I was too lazy to figure out a proper solution.

**Comment by magicprinc** [comment]
> why do you need to customize the timer creation function
I have a custom, single, JVM wide, low memory overhead scheduler. It is used instead of ScheduledThreadPoolExecutor for everything. The main idea: custom DelayedWorkQueue, ScheduledFutureTask (with less fields) and separation of scheduling and target executor (similar to your and Mutiny)

**Comment by magicprinc** [comment]
@Ladicek 
After some optimizations
https://github.com/smallrye/smallrye-fault-tolerance/issues/906
your Timer is more compact than my scheduler,
so I could live without the timer creation function

**Comment by Ladicek** [comment]
I added an integration API to the standalone implementation in #909. I'd be glad to hear if that's good enough for you.

It doesn't include an API to _set_ the timer, I'll try to adopt some of your changes from #906 in another PR. There is an API to observe the timer queue size, which I think is what you needed. Let me know if you need more.

Generally, anything in `io.smallrye.faulttolerance.core` is an internal API that shouldn't be used externally (see also https://github.com/smallrye/smallrye-fault-tolerance/blob/main/implementation/core/src/main/java/io/smallrye/faulttolerance/core/package-info.java).

**Comment by magicprinc** [comment]
@Ladicek It is above any expectations!
