### ISSUE TITLE
Programmatic Asynchronous API is difficult to understand and verbose

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#908]
```CompletionStage<ResultType> FaultTolerance.call( Callable<CompletionStage<ResultType> )``` is a party killer.

Shouldn't it be ```CompletionStage<ResultType> FaultTolerance.call( Callable<ResultType> )```?

It is not obvious, how does it actually work and what does it protect...

**Comment by Ladicek** [comment]
It shouldn't, no. That would only be possible for blocking, thread offload based concurrency, while we also need to support non-blocking, event loop based concurrency. If you only use thread offloads, you can create a simple helper function:

```java
public static <T> CompletionStage<T> wrap(Callable<T> task) {
    try {
        return CompletableFuture.completedFuture(task.call());
    } catch (Exception e) {
        return CompletableFuture.failedFuture(e);
    }
}
```

**Comment by magicprinc** [comment]
It makes sense. 👍

Another unclear moment:

```.withThreadOffload(true)```
+
```.call(()->CompletableFuture.supplyAsync(() -> externalService.hello())```


Does `withThreadOffload(true)` mean that `Callable.call` (== CompletableFuture.supplyAsync) will run in another thread?

CompletableFuture.supplyAsync is a very light operation.
In this case, it makes not much sense.
Could you show more practical example?

**Comment by Ladicek** [comment]
`withThreadOffload(true)` makes sure the guarded operation is executed on an extra thread (the thread pool is not currently configurable, but that's the purpose of #905). If you configure `withThreadOffload(true)`, you don't need to do additional thread offload by `CompletableFuture.supplyAsync()`.

Your code above basically does two thread offloads in a row.
