### ISSUE TITLE
Concept: TimerScheduledThreadPoolExecutor - Low memory footprint ScheduledExecutorService

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#918]
Concept: 
TimerScheduledThreadPoolExecutor 
A low memory footprint ScheduledExecutorService based on ```io.smallrye.faulttolerance.core.timer.Timer```

For using in Mutiny's ```io.smallrye.mutiny.infrastructure.Infrastructure#DEFAULT_SCHEDULER```
instead of MutinyScheduler

https://github.com/magicprinc/smallrye-fault-tolerance/commits/feature/scheduler

**Comment by Ladicek** [comment]
SmallRye Fault Tolerance does not need this. The `Timer` implementation is an internal implementation detail, as is practically everything in `io.smallrye.faulttolerance.core`. You are of course free to copy it and extend to your liking, as this is an open source project, but we won't carry an implementation of something we don't need.
