### ISSUE TITLE
Expose timer through metrics (at least current queue size)

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#919]
Simpler ```io.smallrye.faulttolerance.core.timer.TimerAccess#countScheduledTasks()``` API.

Publishing it as a gauge metric.

https://github.com/magicprinc/smallrye-fault-tolerance/commits/feature/stat

**Comment by Ladicek** [comment]
I want to keep `TimerAccess` a `standalone`-only API, because that should really be a provisional thing until the timer queue (and maybe total number of processed timer tasks?) is exposed through metrics properly. Internally, we have much bigger freedom and probably won't need the kind of API like `TimerAccess`.

I'll reword the title of this issue as a request for exposing timer through metrics.

**Comment by magicprinc** [comment]
I put it here to make it public, but not to draw too much of the orderlies 😅

There are 3 top projects in this area:
1) https://smallrye.io/docs/smallrye-fault-tolerance/6.2.6/index.html
2) https://failsafe.dev/
3) https://resilience4j.readme.io/

SmallRye Fault Tolerance is a state-of-the-art project, and TOP #1:
1) implementation of some kind of standard 👍
2) very easy to learn and use
3) compact, readable, and beautiful source code
4) maintainers don't have NIH syndrome
5) few dependencies and a low memory footprint

There are only three improvements one could wish for:
1) Metrics support in the standalone / Programmatic API (micrometer if you ask)
2) timer queue size in these metrics
3) declarative configuration in spring (support of your annotation in Spring). You could find some ideas here: https://github.com/resilience4j/resilience4j/tree/master/resilience4j-spring 😅

Thank You very much for such amazing product!

**Comment by magicprinc** [comment]
@Ladicek The idea of a small optimization that is not worth a separate ticket. Take a look, maybe it makes sense:

InvocationContext "tuning"

https://github.com/magicprinc/smallrye-fault-tolerance/commits/feature/micro2

**Comment by Ladicek** [comment]
Thanks for your kind words :-) I don't think I'll pursue Spring integration, but I guess it wouldn't be very hard. If you look into the `implementation` directory, the the `fault-tolerance` module is the CDI-based framework built on top of the `core` module. Something similar should be doable for Spring.

Metrics in programmatic API are definitely on the roadmap, but haven't been a priority so far. I should get to it early next year, I hope.
