### ISSUE TITLE
Less noisy FaultTolerance.call API?

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#931]
FaultTolerance.call is declared as throwing Exception.

Often it doesn't throw anything (especially in async mode).

But one need to wrap this call in try {} catch.

Maybe it would be more friendly to remove `throws Exception` and throw Exception (if any) using sneakyThrow ?

**Comment by Ladicek** [comment]
This is a problem where all solutions are bad in one way or another. Synchronously called methods can definitely throw an exception. Asynchronously called methods tend to signal an error by completing erroneously, but it is still possible that an asynchronous call throws an exception -- for example, if a thread pool rejects a task. SmallRye Fault Tolerance does its best to convert these synchronously thrown exceptions to erroneous completion of the future, but it can't guarantee what happens outside of it. So, assuming that `Callable` is the most useful argument that can be passed to `FaultTolerance` methods, the API should in my opinion follow the shape of `Callable`.
