### ISSUE TITLE
Question and thought

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#933]
1) I am really sorry 🙏, but I can't put snapshot build into the production.
Could you please make a release with all those changes since 6.2.6?
 

2) Please see Netty
`io.netty.util.concurrent.AbstractScheduledEventExecutor#defaultCurrentTimeNanos`
they use the same technic I have described in "timer memory optimization"

```
    /**
     * Get the current time in nanoseconds by this executor's clock. This is not the same as {@link System#nanoTime()}
     * for two reasons:
     *
     * <ul>
     *     <li>We apply a fixed offset to the {@link System#nanoTime() nanoTime}</li>
     *     <li>Implementations (in particular EmbeddedEventLoop) may use their own time source so they can control time
     *     for testing purposes.</li>
     * </ul>
     */
    protected long getCurrentTimeNanos() {
        return defaultCurrentTimeNanos();
    }

static long defaultCurrentTimeNanos() {
        return System.nanoTime() - START_TIME;
    }
```

After it, you have positive, small, ever-increasing nanoTime :-) 
You can compare them with < and > without obscure subtraction technic.

**Comment by magicprinc** [comment]
SmallRye Fault Tolerance is on the front page https://github.com/vert-x3/vertx-awesome !

It is time to publish a release (or at least a release candidate) 😅🙏🥂

**Comment by Ladicek** [comment]
6.3.0-RC1 is on its way to Central, it typically doesn't take more than 15 minutes or so.

**Comment by magicprinc** [comment]
@Ladicek Any news about micrometer metrics in standalone mode and release version?

**Comment by Ladicek** [comment]
Not yet, unfortunately. The past few months, I've been busy with the upcoming CDI 4.1 release, but now that it's nearly done, I should have more time for other things. Fingers crossed :-)

**Comment by magicprinc** [comment]
I see: you have developed standalone metrics support. 🔥
I am looking forward to RC :-) 🙏🚀

**Comment by Ladicek** [comment]
6.3.0-RC2 is on its way to Maven Central. Closing this issue, as all requests here have been addressed.
