### ISSUE TITLE
RateLimit: minSpacing violations count towards window limit

### ISSUE THREAD

**Issue by ivangreene** [smallrye/smallrye-fault-tolerance#973]
I have been experimenting with `@RateLimit` for an app contact form: I send an email to myself when a new contact is submitted, but want to rate limit so people can't spam me. So I am working with a larger window than normal (6 per hour) so this is observable

I have noticed that RateLimit will not always reach the 'value' of invocations in the window, if the minSpacing is violated. So for example, if I have 6 invocations per hour, and `minSpacing = 1, minSpacingUnit = SECONDS`, and I submit 6 requests in 1 second, only 1 request makes it through. That is expected. But further spaced out requests within the hour are not invoked. So minSpacing violations count towards the overall window limit. This isn't really what I expected, and I think it's probably not the intention (the docs are not clear on this scenario)

**Comment by ivangreene** [comment]
Looking at the impl, this is clear:
https://github.com/smallrye/smallrye-fault-tolerance/blob/18ee406d673a7521b18612015f6b6cc1ac11b685/implementation/core/src/main/java/io/smallrye/faulttolerance/core/rate/limit/FixedWindow.java#L39-L44
Even if the outcome is to deny invocation based on the minSpacing, we still decrement currentPermits

**Comment by ivangreene** [comment]
And guarded in SmoothWindow: https://github.com/smallrye/smallrye-fault-tolerance/blob/18ee406d673a7521b18612015f6b6cc1ac11b685/implementation/core/src/main/java/io/smallrye/faulttolerance/core/rate/limit/SmoothWindow.java#L45-L47
This should fix it!

**Comment by Ladicek** [comment]
This actually is documented in the javadoc of `@RateLimit`:

> With fixed and rolling time windows, rejected invocations always count towards the limit, so if a caller continuously invokes the guarded method faster than the configuration allows, all invocations are rejected until the caller slows down. With smooth time windows, rejected invocations do not count towards the recent rate of invocations.

Fixed and rolling strategies are fundamentally very different from the smooth strategy. The first two enforce an invocation _count_ in given _time_, while the third enforces invocation _rate_ (given by the limit and time window length).

**Comment by Ladicek** [comment]
I'm adding that paragraph to the reference guide for rate limit as well: #975 

Also, one option you have is to specify the rate limit (if you want fixed or rolling) not as 6 per hour, but 1 per 10 minutes.
