### ISSUE TITLE
FT RateLimit vs competitors

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#994]
Are there any benchmarks and other relevant information about SmallRye FaultTolerance RateLimit **vs** https://bucket4j.com/ and others?

I have to add rate limiting to public API and such information would be very useful.

I want to go with FT, but bucket4j is being suggested by my colleagues.

**Comment by Ladicek** [comment]
Bucket4j is a lot more advanced and feature-full rate limiting library than SmallRye Fault Tolerance will likely ever be, and I don't see anything wrong with using it. If the token bucket approach is what you need, Bucket4j will be a great choice. SmallRye Fault Tolerance certainly shouldn't be _terrible_, but it's a lot more bare-bones compared to Bucket4j.
